'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System.ComponentModel.DataAnnotations
Imports System
Imports System.Collections.Generic

Partial Public Class products
    <Key>
    <Display(Name:="ID")>
    Public Property product_id As Integer

    <Required>
    <Display(Name:="User ID")>
    Public Property user_id As Integer

    <Required>
    <Display(Name:="Product ID")>
    Public Property productinfo_id As Integer

    Public Overridable Property product_info As product_info
    Public Overridable Property users As users

End Class
